---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: 部署web服务
    docker_container:
      name: nginx
      image: nginx:latest
      state: started
      restart: yes
      volumes:
        - /opt/install-service/default.conf:/etc/nginx/conf.d/default.conf
        - /opt/install-service/dist:/usr/share/nginx/html
      ports:
        - "8081:80"
    register: result_nginx

  - name: 验证web服务部署结果
    debug: msg='web服务部署成功'
    when: result_nginx['container']['State']['Status'] == "running"

  - name: web服务部署失败时则提示，否则跳过本任务
    debug: msg="web服务部署失败！"
    when: result_nginx['container']['State']['Status'] != "running"

  - name: 部署消息队列服务
    docker_container:
      name: activemq
      image: webcenter/activemq
      state: started
      restart: yes
      ports:
        - "61613:61613"
        - "61614:61614"
        - "8161:8161"
    register: result_activemq

  - name: 验证消息队列服务部署结果
    debug: msg="消息队列服务部署成功！"
    when: result_activemq['container']['State']['Status'] == "running"

  - name: 消息队列服务部署失败时提示，否则跳过本任务
    debug: msg="消息队列服务部署失败！"
    when: result_activemq['container']['State']['Status'] != "running"

  - name: 显示消息队列服务部署失败原因，成功则跳过本任务
    debug:
      var: result_activemq
      verbosity: 0
    when: result_activemq['container']['State']['Status'] == "running"
