#安装docker
---
- hosts: localhost
  remote_user: root
  gather_facts: false
  tasks:
  - name: 安装devicemapper存储依赖
    yum:
      name: '{{item.soft}}'
      state: present
    with_items:
      - { soft: 'device-mapper-persistent-data' }
      - { soft: 'lvm2' }

  - name: 安装稳定版yum仓库源
    shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: 安装稳定版docker-ce
    yum:
      name: docker-ce
      state: present

  - name: 启动docker服务并允许开机启动
    shell: '{{item.cmd}}'
    with_items:
      - { cmd: 'systemctl start docker' }
      - { cmd: 'systemctl enable docker' }
